const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const alloc = init.arena.allocator();
    var args = std.process.Args.Iterator.init(init.minimal.args);
    _ = args.skip();
    const input_path = args.next() orelse return error.MissingArgument;

    const data = try std.Io.Dir.readFileAlloc(.cwd(), init.io, input_path, alloc, .unlimited);

    var intel_mods: std.ArrayList([]const u8) = .empty;
    var other_mods: std.ArrayList(struct { []const u8, []const u8 }) = .empty;
    var vendors: std.ArrayList([]const u8) = .empty;

    var lines = std.mem.splitScalar(u8, data, '\n');
    while (lines.next()) |line| {
        if (parseName(line, "#define I915_FORMAT_MOD_")) |name|
            try intel_mods.append(alloc, name)
        else if (parseVendorMod(line)) |vm|
            try other_mods.append(alloc, vm)
        else if (parseName(line, "#define DRM_FORMAT_MOD_VENDOR_")) |name|
            try vendors.append(alloc, name);
    }

    var buf: [4096]u8 = undefined;
    var fw = std.Io.File.stdout().writerStreaming(init.io, &buf);
    const w = &fw.interface;

    try w.writeAll("/* AUTOMATICALLY GENERATED by gen_table_fourcc.zig */\nstatic const struct drmFormatModifierInfo drm_format_modifier_table[] = {\n    { DRM_MODIFIER_INVALID(NONE, INVALID) },\n    { DRM_MODIFIER_LINEAR(NONE, LINEAR) },\n");
    for (intel_mods.items) |mod|
        try w.print("    {{ DRM_MODIFIER_INTEL({s}, {s}) }},\n", .{ mod, mod });
    for (other_mods.items) |entry| {
        const vendor, const mod = entry;
        try w.print("    {{ DRM_MODIFIER({s}, {s}, {s}) }},\n", .{ vendor, mod, mod });
    }
    try w.writeAll("};\nstatic const struct drmFormatModifierVendorInfo drm_format_modifier_vendor_table[] = {\n");
    for (vendors.items) |v|
        try w.print("    {{ DRM_FORMAT_MOD_VENDOR_{s}, \"{s}\" }},\n", .{ v, v });
    try w.writeAll("};\n");
    try fw.flush();
}

fn parseName(line: []const u8, prefix: []const u8) ?[]const u8 {
    const trimmed = std.mem.trimStart(u8, line, " \t");
    if (!std.mem.startsWith(u8, trimmed, prefix)) return null;
    const end = std.mem.indexOfAny(u8, trimmed[prefix.len..], " \t\r\n") orelse return null;
    if (end == 0) return null;
    const name = trimmed[prefix.len..][0..end];
    return if (std.mem.indexOfScalar(u8, name, '(') != null) null else name;
}

fn parseVendorMod(line: []const u8) ?struct { []const u8, []const u8 } {
    const trimmed = std.mem.trimStart(u8, line, " \t");
    const prefix = "#define DRM_FORMAT_MOD_";
    if (!std.mem.startsWith(u8, trimmed, prefix)) return null;
    const after = trimmed[prefix.len..];

    for ([_][]const u8{ "ARM", "SAMSUNG", "QCOM", "VIVANTE", "NVIDIA", "BROADCOM", "ALLWINNER" }) |vendor| {
        if (!std.mem.startsWith(u8, after, vendor) or after.len <= vendor.len or after[vendor.len] != '_') continue;
        const mod_start = vendor.len + 1;
        const end = std.mem.indexOfAny(u8, after[mod_start..], " \t\r\n") orelse continue;
        if (end == 0) continue;
        const mod = after[mod_start..][0..end];
        if (std.mem.indexOfScalar(u8, mod, '(') != null) continue;
        if (std.mem.eql(u8, vendor, "ARM") and
            (std.mem.eql(u8, mod, "TYPE_AFBC") or std.mem.eql(u8, mod, "TYPE_MISC") or std.mem.eql(u8, mod, "TYPE_AFRC"))) continue;
        return .{ vendor, mod };
    }
    return null;
}
