const std = @import("std");
const Io = std.Io;

pub fn main(init: std.process.Init) !void {
    const alloc = init.arena.allocator();
    const io = init.io;

    var args = std.process.Args.Iterator.init(init.minimal.args);
    _ = args.skip();
    const input_path = args.next() orelse return error.MissingArgument;

    const data = try Io.Dir.readFileAlloc(.cwd(), io, input_path, alloc, .unlimited);

    var intel_mods: std.ArrayList([]const u8) = .empty;
    var other_mods: std.ArrayList(struct { []const u8, []const u8 }) = .empty;
    var vendors: std.ArrayList([]const u8) = .empty;

    var lines = std.mem.splitScalar(u8, data, '\n');
    while (lines.next()) |line| {
        if (parseAfter(line, "#define I915_FORMAT_MOD_")) |name| {
            try intel_mods.append(alloc, name);
        } else if (parseVendorMod(line)) |vm| {
            try other_mods.append(alloc, vm);
        } else if (parseAfter(line, "#define DRM_FORMAT_MOD_VENDOR_")) |name| {
            try vendors.append(alloc, name);
        }
    }

    var buf: [4096]u8 = undefined;
    var fw = Io.File.stdout().writerStreaming(io, &buf);
    const w = &fw.interface;

    try w.writeAll(
        \\/* AUTOMATICALLY GENERATED by gen_table_fourcc.zig */
        \\static const struct drmFormatModifierInfo drm_format_modifier_table[] = {
        \\    { DRM_MODIFIER_INVALID(NONE, INVALID) },
        \\    { DRM_MODIFIER_LINEAR(NONE, LINEAR) },
        \\
    );

    for (intel_mods.items) |mod|
        try w.print("    {{ DRM_MODIFIER_INTEL({s}, {s}) }},\n", .{ mod, mod });

    for (other_mods.items) |entry| {
        const vendor, const mod = entry;
        try w.print("    {{ DRM_MODIFIER({s}, {s}, {s}) }},\n", .{ vendor, mod, mod });
    }

    try w.writeAll(
        \\};
        \\static const struct drmFormatModifierVendorInfo drm_format_modifier_vendor_table[] = {
        \\
    );

    for (vendors.items) |v|
        try w.print("    {{ DRM_FORMAT_MOD_VENDOR_{s}, \"{s}\" }},\n", .{ v, v });

    try w.writeAll("};\n");
    try fw.flush();
}

fn parseAfter(line: []const u8, prefix: []const u8) ?[]const u8 {
    const trimmed = std.mem.trimStart(u8, line, " \t");
    if (!std.mem.startsWith(u8, trimmed, prefix)) return null;
    const after = trimmed[prefix.len..];
    const end = std.mem.indexOfAny(u8, after, " \t\r\n") orelse return null;
    if (end == 0) return null;
    const name = after[0..end];
    if (std.mem.indexOfScalar(u8, name, '(') != null) return null;
    return name;
}

fn parseVendorMod(line: []const u8) ?struct { []const u8, []const u8 } {
    const prefix = "#define DRM_FORMAT_MOD_";
    const trimmed = std.mem.trimStart(u8, line, " \t");
    if (!std.mem.startsWith(u8, trimmed, prefix)) return null;
    const after = trimmed[prefix.len..];

    for ([_][]const u8{ "ARM", "SAMSUNG", "QCOM", "VIVANTE", "NVIDIA", "BROADCOM", "ALLWINNER" }) |vendor| {
        if (std.mem.startsWith(u8, after, vendor) and after.len > vendor.len and after[vendor.len] == '_') {
            const mod_start = vendor.len + 1;
            // Require trailing whitespace (like the Python regex `\s` at end)
            const end = std.mem.indexOfAny(u8, after[mod_start..], " \t\r\n") orelse continue;
            if (end == 0) continue;
            const mod = after[mod_start..][0..end];
            if (std.mem.indexOfScalar(u8, mod, '(') != null) continue;
            if (std.mem.eql(u8, vendor, "ARM") and
                (std.mem.eql(u8, mod, "TYPE_AFBC") or
                    std.mem.eql(u8, mod, "TYPE_MISC") or
                    std.mem.eql(u8, mod, "TYPE_AFRC"))) continue;
            return .{ vendor, mod };
        }
    }
    return null;
}
